sudo: false
language: php

env:
    global:
        - TASK_TESTS_COVERAGE=1

matrix:
    fast_finish: true
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
          env: TASK_TESTS_COVERAGE=0

        # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
        - php: hhvm-3.9
          env: TASK_TESTS_COVERAGE=0
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm
          env: TASK_TESTS_COVERAGE=0
          sudo: required
          dist: trusty
          group: edge

before_script:
  - if [ -n "$GITHUB_OAUTH_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_OAUTH_TOKEN}; fi;
  - composer update
script:
  - if [ $TASK_TESTS_COVERAGE == 1 ]; then vendor/bin/codecept run -v --steps  --coverage --coverage-xml --coverage-html; fi
  - if [ $TASK_TESTS_COVERAGE == 0 ]; then vendor/bin/codecept run unit,acceptance -v --steps; fi
cache:
  directories:
    - $HOME/.composer/cache